[manager]
layout         = [ 1, 4, 3 ]
sort_by        = "modified"
sort_sensitive = true
sort_reverse   = true
sort_dir_first = true
show_hidden    = true
show_symlink   = true

[preview]
tab_size   = 2
max_width  = 600
max_height = 900
cache_dir  = ""

[opener]
folder = [
	{ exec = 'open -R "$@"', display_name = "Reveal in Finder - Unix" },
	{ exec = 'nvim "$@"', display_name = "Open in Neovim - Unix" },
	{ exec = 'neovide "$@"', display_name = "Open in Neovide - Unix" },
	{ exec = 'explorer "%*"', display_name = "Reveal in Finder - Windows" },
	{ exec = 'nvim "%*"', display_name = "Open in Neovim - Windows" },
	{ exec = 'neovide "%*"', display_name = "Open in Neovide - Windows" },
	{ exec = '$EDITOR "$@"', display_name = "Open in $EDITOR" },
]
archive = [
	{ exec = 'unar "$1"', display_name = "Extract here" },
    { exec = 'pwsh -c "Start-Process `"$@`""', display_name = "Open Default - Unix" },
    { exec = 'pwsh -c "Start-Process `"%*`""', display_name = "Open Default - Windows" },
]
text = [
	{ exec = 'nvim "$@"', display_name = "Open in Neovim - Unix", block = true },
	{ exec = 'neovide "$@"', display_name = "Open in Neovide - Unix", block = true },
	{ exec = 'nvim "%*"', display_name = "Open in Neovim - Windows", block = true },
	{ exec = 'neovide "%*"', display_name = "Open in Neovide - Windows", block = true },
	{ exec = '$EDITOR "$@"', display_name = "Open in $EDITOR", block = true },
    { exec = 'pwsh -c "Start-Process `"$@`""', display_name = "Open Default - Unix" },
    { exec = 'pwsh -c "Start-Process `"%*`""', display_name = "Open Default - Windows" },
]
image = [
	{ exec = 'open "$@"', display_name = "Open" },
	{ exec = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, display_name = "Show EXIF" },
    { exec = 'pwsh -c "Start-Process `"$@`""', display_name = "Open Default - Unix" },
    { exec = 'pwsh -c "Start-Process `"%*`""', display_name = "Open Default - Windows" },
]
video = [
	{ exec = 'mpv "$@"' },
	{ exec = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, display_name = "Show media info" },
    { exec = 'pwsh -c "Start-Process `"$@`""', display_name = "Open Default - Unix" },
    { exec = 'pwsh -c "Start-Process `"%*`""', display_name = "Open Default - Windows" },
]
audio = [
	{ exec = 'mpv "$@"' },
	{ exec = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, display_name = "Show media info" },
    { exec = 'pwsh -c "Start-Process `"$@`""', display_name = "Open Default - Unix" },
    { exec = 'pwsh -c "Start-Process `"%*`""', display_name = "Open Default - Windows" },
]
fallback = [
	{ exec = 'open "$@"', display_name = "Open" },
	{ exec = 'open -R "$@"', display_name = "Reveal in Finder" },
	{ exec = 'explorer "%*"', display_name = "Reveal in Finder - Windows" },
	{ exec = 'nvim "$@"', display_name = "Open in Neovim - Unix" },
	{ exec = 'neovide "$@"', display_name = "Open in Neovide - Unix" },
	{ exec = 'nvim "%*"', display_name = "Open in Neovim - Windows" },
	{ exec = 'neovide "%*"', display_name = "Open in Neovide - Windows" },
    { exec = 'pwsh -c "Start-Process `"$@`""', display_name = "Open Default - Unix" },
    { exec = 'pwsh -c "Start-Process `"%*`""', display_name = "Open Default - Windows" },
]

[open]
rules = [
	{ name = "*/", use = "folder" },

	{ mime = "text/*", use = "text" },
	{ mime = "image/*", use = "image" },
	{ mime = "video/*", use = "video" },
	{ mime = "audio/*", use = "audio" },
	{ mime = "inode/x-empty", use = "text" },

	{ mime = "application/json", use = "text" },
	{ mime = "*/javascript", use = "text" },

	{ mime = "application/zip", use = "archive" },
	{ mime = "application/gzip", use = "archive" },
	{ mime = "application/x-tar", use = "archive" },
	{ mime = "application/x-bzip", use = "archive" },
	{ mime = "application/x-bzip2", use = "archive" },
	{ mime = "application/x-7z-compressed", use = "archive" },
	{ mime = "application/x-rar", use = "archive" },

	{ mime = "*", use = "fallback" },
    { name = "*.*", use = "fallback" },
    { name = "*/*", use = "fallback" },
]

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

# [plugins]
# preload = []

[log]
enabled = false
