enable_nightly_info=true
enable_release_build=false
# downloads_location=""
# installation_location=""
version_sync_file_location="/home/patryk/.config/nvim/nvim_version"
rollback_limit=3
# github_mirror=""
